// flow-typed signature: 5be5baa379bd0fdd93184e5afe77a085
// flow-typed version: <<STUB>>/babel-plugin-s2s-reducer-root_v^0.1.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-s2s-reducer-root'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-s2s-reducer-root' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-s2s-reducer-root/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-s2s-reducer-root/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-s2s-reducer-root/lib/index'>;
}
