// flow-typed signature: 4e0f758d1e7948924dc1714a7ad4c4c7
// flow-typed version: <<STUB>>/babel-plugin-s2s-action-root_v^0.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-s2s-action-root'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-s2s-action-root' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-s2s-action-root/lib/__fixtures__/app/actionTypes' {
  declare module.exports: any;
}

declare module 'babel-plugin-s2s-action-root/lib/__fixtures__/bob/actionTypes' {
  declare module.exports: any;
}

declare module 'babel-plugin-s2s-action-root/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-s2s-action-root/lib/__fixtures__/app/actionTypes.js' {
  declare module.exports: $Exports<'babel-plugin-s2s-action-root/lib/__fixtures__/app/actionTypes'>;
}
declare module 'babel-plugin-s2s-action-root/lib/__fixtures__/bob/actionTypes.js' {
  declare module.exports: $Exports<'babel-plugin-s2s-action-root/lib/__fixtures__/bob/actionTypes'>;
}
declare module 'babel-plugin-s2s-action-root/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-s2s-action-root/lib/index'>;
}
