// flow-typed signature: 76e906a73e696f3e85a28aba5890de38
// flow-typed version: <<STUB>>/mosca_v^2.5.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mosca'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mosca' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mosca/examples/kafka/server' {
  declare module.exports: any;
}

declare module 'mosca/examples/mosca-tree/firstConfig' {
  declare module.exports: any;
}

declare module 'mosca/examples/mosca-tree/secondConfig' {
  declare module.exports: any;
}

declare module 'mosca/examples/mosca-tree/thirdConfig' {
  declare module.exports: any;
}

declare module 'mosca/examples/redis/firstConfig' {
  declare module.exports: any;
}

declare module 'mosca/examples/redis/secondConfig' {
  declare module.exports: any;
}

declare module 'mosca/examples/rule_engine/broker' {
  declare module.exports: any;
}

declare module 'mosca/examples/secure/secureClient' {
  declare module.exports: any;
}

declare module 'mosca/examples/secure/secureEmbedded' {
  declare module.exports: any;
}

declare module 'mosca/examples/secure/secureServer' {
  declare module.exports: any;
}

declare module 'mosca/examples/Server_With_All_Interfaces-Settings' {
  declare module.exports: any;
}

declare module 'mosca/lib/authorizer' {
  declare module.exports: any;
}

declare module 'mosca/lib/cli' {
  declare module.exports: any;
}

declare module 'mosca/lib/client' {
  declare module.exports: any;
}

declare module 'mosca/lib/interfaces' {
  declare module.exports: any;
}

declare module 'mosca/lib/options' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/abstract' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/index' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/levelup' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/matcher' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/memory' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/mongo' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/redis' {
  declare module.exports: any;
}

declare module 'mosca/lib/persistence/utils' {
  declare module.exports: any;
}

declare module 'mosca/lib/serializers' {
  declare module.exports: any;
}

declare module 'mosca/lib/server' {
  declare module.exports: any;
}

declare module 'mosca/lib/stats' {
  declare module.exports: any;
}

declare module 'mosca/public/mqtt' {
  declare module.exports: any;
}

declare module 'mosca/test/abstract_server' {
  declare module.exports: any;
}

declare module 'mosca/test/authorizer' {
  declare module.exports: any;
}

declare module 'mosca/test/cli' {
  declare module.exports: any;
}

declare module 'mosca/test/common' {
  declare module.exports: any;
}

declare module 'mosca/test/helpers/createConnection' {
  declare module.exports: any;
}

declare module 'mosca/test/helpers/createSecureConnection' {
  declare module.exports: any;
}

declare module 'mosca/test/helpers/createSecureWebsocketConnection' {
  declare module.exports: any;
}

declare module 'mosca/test/helpers/createWebsocketConnection' {
  declare module.exports: any;
}

declare module 'mosca/test/options' {
  declare module.exports: any;
}

declare module 'mosca/test/persistence/abstract' {
  declare module.exports: any;
}

declare module 'mosca/test/persistence/levelup_spec' {
  declare module.exports: any;
}

declare module 'mosca/test/persistence/memory_spec' {
  declare module.exports: any;
}

declare module 'mosca/test/persistence/mongo_spec' {
  declare module.exports: any;
}

declare module 'mosca/test/persistence/redis_spec' {
  declare module.exports: any;
}

declare module 'mosca/test/persistence/utils_spec' {
  declare module.exports: any;
}

declare module 'mosca/test/sample_config' {
  declare module.exports: any;
}

declare module 'mosca/test/server_mongo' {
  declare module.exports: any;
}

declare module 'mosca/test/server_redis' {
  declare module.exports: any;
}

declare module 'mosca/test/server_secure' {
  declare module.exports: any;
}

declare module 'mosca/test/server_websocket_attach' {
  declare module.exports: any;
}

declare module 'mosca/test/server_websocket_secure' {
  declare module.exports: any;
}

declare module 'mosca/test/server_websocket' {
  declare module.exports: any;
}

declare module 'mosca/test/server' {
  declare module.exports: any;
}

declare module 'mosca/test/stats' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mosca/examples/kafka/server.js' {
  declare module.exports: $Exports<'mosca/examples/kafka/server'>;
}
declare module 'mosca/examples/mosca-tree/firstConfig.js' {
  declare module.exports: $Exports<'mosca/examples/mosca-tree/firstConfig'>;
}
declare module 'mosca/examples/mosca-tree/secondConfig.js' {
  declare module.exports: $Exports<'mosca/examples/mosca-tree/secondConfig'>;
}
declare module 'mosca/examples/mosca-tree/thirdConfig.js' {
  declare module.exports: $Exports<'mosca/examples/mosca-tree/thirdConfig'>;
}
declare module 'mosca/examples/redis/firstConfig.js' {
  declare module.exports: $Exports<'mosca/examples/redis/firstConfig'>;
}
declare module 'mosca/examples/redis/secondConfig.js' {
  declare module.exports: $Exports<'mosca/examples/redis/secondConfig'>;
}
declare module 'mosca/examples/rule_engine/broker.js' {
  declare module.exports: $Exports<'mosca/examples/rule_engine/broker'>;
}
declare module 'mosca/examples/secure/secureClient.js' {
  declare module.exports: $Exports<'mosca/examples/secure/secureClient'>;
}
declare module 'mosca/examples/secure/secureEmbedded.js' {
  declare module.exports: $Exports<'mosca/examples/secure/secureEmbedded'>;
}
declare module 'mosca/examples/secure/secureServer.js' {
  declare module.exports: $Exports<'mosca/examples/secure/secureServer'>;
}
declare module 'mosca/examples/Server_With_All_Interfaces-Settings.js' {
  declare module.exports: $Exports<'mosca/examples/Server_With_All_Interfaces-Settings'>;
}
declare module 'mosca/index' {
  declare module.exports: $Exports<'mosca'>;
}
declare module 'mosca/index.js' {
  declare module.exports: $Exports<'mosca'>;
}
declare module 'mosca/lib/authorizer.js' {
  declare module.exports: $Exports<'mosca/lib/authorizer'>;
}
declare module 'mosca/lib/cli.js' {
  declare module.exports: $Exports<'mosca/lib/cli'>;
}
declare module 'mosca/lib/client.js' {
  declare module.exports: $Exports<'mosca/lib/client'>;
}
declare module 'mosca/lib/interfaces.js' {
  declare module.exports: $Exports<'mosca/lib/interfaces'>;
}
declare module 'mosca/lib/options.js' {
  declare module.exports: $Exports<'mosca/lib/options'>;
}
declare module 'mosca/lib/persistence/abstract.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/abstract'>;
}
declare module 'mosca/lib/persistence/index.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/index'>;
}
declare module 'mosca/lib/persistence/levelup.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/levelup'>;
}
declare module 'mosca/lib/persistence/matcher.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/matcher'>;
}
declare module 'mosca/lib/persistence/memory.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/memory'>;
}
declare module 'mosca/lib/persistence/mongo.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/mongo'>;
}
declare module 'mosca/lib/persistence/redis.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/redis'>;
}
declare module 'mosca/lib/persistence/utils.js' {
  declare module.exports: $Exports<'mosca/lib/persistence/utils'>;
}
declare module 'mosca/lib/serializers.js' {
  declare module.exports: $Exports<'mosca/lib/serializers'>;
}
declare module 'mosca/lib/server.js' {
  declare module.exports: $Exports<'mosca/lib/server'>;
}
declare module 'mosca/lib/stats.js' {
  declare module.exports: $Exports<'mosca/lib/stats'>;
}
declare module 'mosca/public/mqtt.js' {
  declare module.exports: $Exports<'mosca/public/mqtt'>;
}
declare module 'mosca/test/abstract_server.js' {
  declare module.exports: $Exports<'mosca/test/abstract_server'>;
}
declare module 'mosca/test/authorizer.js' {
  declare module.exports: $Exports<'mosca/test/authorizer'>;
}
declare module 'mosca/test/cli.js' {
  declare module.exports: $Exports<'mosca/test/cli'>;
}
declare module 'mosca/test/common.js' {
  declare module.exports: $Exports<'mosca/test/common'>;
}
declare module 'mosca/test/helpers/createConnection.js' {
  declare module.exports: $Exports<'mosca/test/helpers/createConnection'>;
}
declare module 'mosca/test/helpers/createSecureConnection.js' {
  declare module.exports: $Exports<'mosca/test/helpers/createSecureConnection'>;
}
declare module 'mosca/test/helpers/createSecureWebsocketConnection.js' {
  declare module.exports: $Exports<'mosca/test/helpers/createSecureWebsocketConnection'>;
}
declare module 'mosca/test/helpers/createWebsocketConnection.js' {
  declare module.exports: $Exports<'mosca/test/helpers/createWebsocketConnection'>;
}
declare module 'mosca/test/options.js' {
  declare module.exports: $Exports<'mosca/test/options'>;
}
declare module 'mosca/test/persistence/abstract.js' {
  declare module.exports: $Exports<'mosca/test/persistence/abstract'>;
}
declare module 'mosca/test/persistence/levelup_spec.js' {
  declare module.exports: $Exports<'mosca/test/persistence/levelup_spec'>;
}
declare module 'mosca/test/persistence/memory_spec.js' {
  declare module.exports: $Exports<'mosca/test/persistence/memory_spec'>;
}
declare module 'mosca/test/persistence/mongo_spec.js' {
  declare module.exports: $Exports<'mosca/test/persistence/mongo_spec'>;
}
declare module 'mosca/test/persistence/redis_spec.js' {
  declare module.exports: $Exports<'mosca/test/persistence/redis_spec'>;
}
declare module 'mosca/test/persistence/utils_spec.js' {
  declare module.exports: $Exports<'mosca/test/persistence/utils_spec'>;
}
declare module 'mosca/test/sample_config.js' {
  declare module.exports: $Exports<'mosca/test/sample_config'>;
}
declare module 'mosca/test/server_mongo.js' {
  declare module.exports: $Exports<'mosca/test/server_mongo'>;
}
declare module 'mosca/test/server_redis.js' {
  declare module.exports: $Exports<'mosca/test/server_redis'>;
}
declare module 'mosca/test/server_secure.js' {
  declare module.exports: $Exports<'mosca/test/server_secure'>;
}
declare module 'mosca/test/server_websocket_attach.js' {
  declare module.exports: $Exports<'mosca/test/server_websocket_attach'>;
}
declare module 'mosca/test/server_websocket_secure.js' {
  declare module.exports: $Exports<'mosca/test/server_websocket_secure'>;
}
declare module 'mosca/test/server_websocket.js' {
  declare module.exports: $Exports<'mosca/test/server_websocket'>;
}
declare module 'mosca/test/server.js' {
  declare module.exports: $Exports<'mosca/test/server'>;
}
declare module 'mosca/test/stats.js' {
  declare module.exports: $Exports<'mosca/test/stats'>;
}
