// flow-typed signature: 628281716f6e01682d126ba3fc605a84
// flow-typed version: <<STUB>>/react-scroll-to-component_v^1.0.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scroll-to-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scroll-to-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-scroll-to-component/index' {
  declare module.exports: $Exports<'react-scroll-to-component'>;
}
declare module 'react-scroll-to-component/index.js' {
  declare module.exports: $Exports<'react-scroll-to-component'>;
}
